- name: split function in ansible 
  hosts: local
  connection: local
  vars:
    tags:
      Application: payment
      Environment: dev

  tasks:
  - name: Convert map to list
    ansible.builtin.debug:
      msg: "Techologies are:: {{ technologies | dict2items }}"

