- name: Convert to Upper characters
  hosts: local
  connection: local
  vars:
    name: "Sindhuja Muddana"

  tasks:
  - name: Convert to upper characters
    ansible.builtin.debug:
      msg: "{{ name | upper }}"