- name: Storing the input in a varaible and display the output.
  hosts: local
  connection: local

  tasks:
  - name: grep for root
    ansible.builtin.shell: cat /etc/passwd | grep root
    register: result

  - name: print the output
    ansible.builtin.debug:
      msg: "{{ result }}"

