- name: user creation
  hosts: local
  connection: local
  become: yes

  tasks:
  - name: check user exists or not
    ansible.builtin.shell: id roboshop
    register: user_output
    ignore_errors: true

  - name: print the output
    ansible.builtin.debug:
      msg: "{{ user_output }}"