# This is my play-01
- name: PLAY-01
  hosts: ip-172-31-24-43.ec2.internal
  tasks:
  - name: PLAY-01 and TASK-01
    ansible.builtin.debug:   # mainly used to print messages, variables and structured data.
      msg: "Hello from PLAY-01 and TASK-01"

  - name: PLAY-01 and TASK-02
    ansible.builtin.debug:
      msg: "Hello from PLAY-01 and TASK-02"